# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axis_subset_converter_0_0/VGA_top_axis_subset_converter_0_0.xci
# IP: The module: 'VGA_top_axis_subset_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axis_subset_converter_0_0/VGA_top_axis_subset_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axis_subset_converter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axis_subset_converter_0_0/VGA_top_axis_subset_converter_0_0.xci
# IP: The module: 'VGA_top_axis_subset_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axis_subset_converter_0_0/VGA_top_axis_subset_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axis_subset_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
