# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/zedboard_constraints.xdc

# XDC: new/debug.xdc

# Block Designs: bd/VGA_top/VGA_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top || ORIG_REF_NAME==VGA_top} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_processing_system7_0_0/VGA_top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_processing_system7_0_0 || ORIG_REF_NAME==VGA_top_processing_system7_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_rst_ps7_0_100M_0/VGA_top_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==VGA_top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_axi_vdma_0_1 || ORIG_REF_NAME==VGA_top_axi_vdma_0_1} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_axi_smc_0/VGA_top_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_axi_smc_0 || ORIG_REF_NAME==VGA_top_axi_smc_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_ps7_0_axi_periph_0/VGA_top_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_ps7_0_axi_periph_0 || ORIG_REF_NAME==VGA_top_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_xbar_0/VGA_top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_xbar_0 || ORIG_REF_NAME==VGA_top_xbar_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_v_axi4s_vid_out_0_0/VGA_top_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==VGA_top_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_v_tc_0_0/VGA_top_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_v_tc_0_0 || ORIG_REF_NAME==VGA_top_v_tc_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_vidcut_0_0/VGA_top_vidcut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_vidcut_0_0 || ORIG_REF_NAME==VGA_top_vidcut_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_axis_subset_converter_0_0/VGA_top_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_axis_subset_converter_0_0 || ORIG_REF_NAME==VGA_top_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_xlconcat_0_0/VGA_top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_xlconcat_0_0 || ORIG_REF_NAME==VGA_top_xlconcat_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_auto_pc_0/VGA_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_auto_pc_0 || ORIG_REF_NAME==VGA_top_auto_pc_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_axi_intc_0_0/VGA_top_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_axi_intc_0_0 || ORIG_REF_NAME==VGA_top_axi_intc_0_0} -quiet] -quiet

# XDC: bd/VGA_top/VGA_top_ooc.xdc
