# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.cache/wt [current_project]
set_property parent.project_path /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/john/vivadoproject/ip_repo/VGA_disp_1.0
  /home/john/vivadoproject/vidcut/vidcut.srcs/sources_1/new
  /home/john/vivadoproject/VGA_mem_mapped-master/VGA_1_0_D
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/hdl/VGA_top_wrapper.vhd
add_files /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/VGA_top.bd
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_processing_system7_0_0/VGA_top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_rst_ps7_0_100M_0/VGA_top_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_rst_ps7_0_100M_0/VGA_top_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_rst_ps7_0_100M_0/VGA_top_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_smc_0/bd_0/ip/ip_1/bd_a948_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_smc_0/bd_0/ip/ip_1/bd_a948_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_smc_0/bd_0/ip/ip_5/bd_a948_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_smc_0/bd_0/ip/ip_6/bd_a948_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_smc_0/bd_0/ip/ip_7/bd_a948_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_smc_0/bd_0/ip/ip_8/bd_a948_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_xbar_0/VGA_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_v_axi4s_vid_out_0_0/VGA_top_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_v_axi4s_vid_out_0_0/VGA_top_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_v_tc_0_0/VGA_top_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_v_tc_0_0/VGA_top_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axis_subset_converter_0_0/VGA_top_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_auto_pc_0/VGA_top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_intc_0_0/VGA_top_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_intc_0_0/VGA_top_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_intc_0_0/VGA_top_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/VGA_top_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/john/vivadoproject/VGA_mem_mapped-master/zedboard_constraints.xdc
set_property used_in_implementation false [get_files /home/john/vivadoproject/VGA_mem_mapped-master/zedboard_constraints.xdc]

read_xdc /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top VGA_top_wrapper -part xc7z020clg484-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VGA_top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VGA_top_wrapper_utilization_synth.rpt -pb VGA_top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
