# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1.xci
# IP: The module: 'VGA_top_axi_vdma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1.xci
# IP: The module: 'VGA_top_axi_vdma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/john/vivadoproject/VGA_mem_mapped-master/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_axi_vdma_0_1/VGA_top_axi_vdma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
